services:
  app:
    build: ./mastra-app
    ports:
      - "4111:4111"
    volumes:
      - ./mastra-app:/app
      - ./mastra-app/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    tty: true
    stdin_open: true